CREATE TABLE FACTS AS
(SELECT 
    LOCATION PROVINCE_WITH_MAXIMUM_CASES, ISLAND ISLAND_WITH_MAXIMUM_CASES,
    (SELECT province
FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_TARUN_PRAJAPATI
WHERE province IS NOT null  ORDER BY New_Cases DESC LIMIT 1) PROVINCE_WITH_Max_Daily_New_Cases,
(SELECT island 
FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_TARUN_PRAJAPATI
WHERE island IS NOT null ORDER BY New_Cases DESC LIMIT 1) ISLAND_WITH_Max_Daily_New_Cases,
(SELECT Date
FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_TARUN_PRAJAPATI
ORDER BY TOTAL_CASES DESC LIMIT 1) DAY_WITH_MAXIMUM_CASES,
(SELECT TOTAL_CASES
FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_TARUN_PRAJAPATI
ORDER BY TOTAL_CASES DESC LIMIT 1) MAXIMUM_CASES_IN_A_DAY,
(SELECT SUM(Total_Cases) Total_Cases
FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_TARUN_PRAJAPATI
GROUP BY Month(DATE(date)), Year(DATE(date)) ORDER BY   Total_Cases DESC LIMIT 1)MAXIMUM_CASES_IN_A_MONTH
FROM 
    FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_TARUN_PRAJAPATI
WHERE NOT LOCATION = 'Indonesia'
ORDER BY TOTAL_CASES DESC LIMIT 1
)